# -*- coding: utf-8 -*-
"""
Created on Mon Sep  9 16:55:39 2019

@author: kalya
"""
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,5), ["A", "B", "C", "D", "E"], ["U", "V", "W", "X", "Y"])
print(df)
print("\n")
print(df["U"])
print("\n")
print(df.U)
print("\n")
print(df[["U","V"]])
print("\n")
df["N"] = df["U"] + df["W"]
print(df)
print("\n")
df.drop("N", axis=1)
print(df)
print("\n")
df.drop("N", axis=1, inplace=True)
print(df)
print("\n")
print(df.drop("Y", axis=1))
print("\n")
df.drop("E", inplace=True)
print(df)
print("\n")
print(df.shape)
print("\n")
print(df[["Y", "X"]])
print("\n")
print(df.loc["B"])
print("\n")
print(df.iloc[1])
print("\n")
print(df.loc[["A","B"]])
print("\n")
print(df.iloc[[0,1]])
print("\n")
print(df.loc["B","U"])
print("\n")
print(df.iloc[1,0])
print("\n")
print(df.loc[["A","B","C"],["U","V","W"]])
print("\n")
print(df)
print("\n")
print(df[df<0.5])
print("\n")
print(df[df["V"]<0.5])
print("\n")
print(df[df["Y"]<0])
print("\n")
print(df[df["X"]<0])
print("\n")
print(df[df["X"]<0]["W"])
print("\n")
print(df[df["X"]<0][["W","Y"]])
print("\n")
print(df[df["X"]<0])
print("\n")
print(df[(df["X"]<0) & (df["Y"]<0)][["W","Y"]])
print("\n")